const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim shirts",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "Hign quality products",
    },
    {
      _id: "2",
      name: "Addidas shirt",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 0,
      brand: "Addidas",
      rating: 4,
      numReviews: 10,
      description: "Hign quality products",
    },
    {
      _id: "3",
      name: "Puma pants",
      category: "pants",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Puma",
      rating: 3,
      numReviews: 10,
      description: "Hign quality products",
    },
    {
      _id: "4",
      name: "Raymond shirt",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      description: "Hign quality products",
    },
    {
      _id: "5",
      name: "Nike Trowser",
      category: "Trowsers",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "Hign quality products",
    },
    {
      _id: "6",
      name: "Wrangler pants",
      category: "Pants",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Wrangler",
      rating: 1,
      numReviews: 10,
      description: "Hign quality products",
    },
    {
      _id: "7",
      name: "Nike Slim shirts",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "Hign quality products",
    },
    {
      _id: "8",
      name: "Nike Slim shirts",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "Hign quality products",
    },
  ],
};

export default data;
